name: Scrape data

on:
  push:
    branches:
      - master
  schedule:
    # Customize to whatever interval you need:
    # https://crontab.guru/every-5-minutes
    - cron:  '0 * * * *'

jobs:
  scrape:
    name: Scrape
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm run scrape
